package sistem.Presentacion;
import sistem.Entidades.Validaciones;
import sistem.Dao.*;
import sistem.LogicaNegocio.*;
import sistem.Entidades.*;

/**
 * nombre de la clase: Frm_Autor
 * version:1.0
 * fecha: 23/08/19
 * copyright:ITCA-FEPADE
 * @author Brenda Ramos
 */
public class Frm_Autor extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_Autor
     */
    Validaciones v= new Validaciones();
    TransAutor ob=new TransAutor();
    public Frm_Autor() {
        initComponents(); 
        v.validarNombres(txtNomAuto);
        v.validarNombres(txtNaciAutor);
        v.validarNombres(txtSeudonimo);
        llenar();
    }
    void llenar(){
      TableAutor.setModel(ob.datos());
    }
    void limpiar()
    {
        txtCodAut.setText("");
        txtNaciAutor.setText("");
        txtNomAuto.setText("");
        txtSeudonimo.setText("");
        buttonGroup1.clearSelection();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelAutor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodAut = new javax.swing.JTextField();
        txtNomAuto = new javax.swing.JTextField();
        txtNaciAutor = new javax.swing.JTextField();
        rbtnMasculino = new javax.swing.JRadioButton();
        rbtnFemenino = new javax.swing.JRadioButton();
        btnAgregarAuto = new javax.swing.JButton();
        btnModifAutor = new javax.swing.JButton();
        btnElimAutor = new javax.swing.JButton();
        btnSalirAutor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSeudonimo = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAutor = new javax.swing.JTable();

        setTitle("Autores");
        setVisible(true);

        jLabel1.setText("Código");

        jLabel2.setText("Nombre");

        jLabel3.setText("Nacionalidad");

        jLabel4.setText("Genero");

        txtCodAut.setEnabled(false);

        buttonGroup1.add(rbtnMasculino);
        rbtnMasculino.setText("Masculino");

        buttonGroup1.add(rbtnFemenino);
        rbtnFemenino.setText("Femenino");

        btnAgregarAuto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/agregar-boton-dentro-del-circulo-negro.png"))); // NOI18N
        btnAgregarAuto.setText("Agregar");
        btnAgregarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAutoActionPerformed(evt);
            }
        });

        btnModifAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/lapiz-escribiendo-en-un-papel.png"))); // NOI18N
        btnModifAutor.setText("Modificar");
        btnModifAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifAutorActionPerformed(evt);
            }
        });

        btnElimAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/cesto-de-basura.png"))); // NOI18N
        btnElimAutor.setText("Eliminar");
        btnElimAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimAutorActionPerformed(evt);
            }
        });

        btnSalirAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/logout.png"))); // NOI18N
        btnSalirAutor.setText("Salir");
        btnSalirAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirAutorActionPerformed(evt);
            }
        });

        jLabel5.setText("Seudonimo");

        txtestado.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        txtestado.setText("0");
        txtestado.setBorder(null);
        txtestado.setEnabled(false);

        javax.swing.GroupLayout panelAutorLayout = new javax.swing.GroupLayout(panelAutor);
        panelAutor.setLayout(panelAutorLayout);
        panelAutorLayout.setHorizontalGroup(
            panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutorLayout.createSequentialGroup()
                .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAutorLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelAutorLayout.createSequentialGroup()
                                    .addGap(58, 58, 58)
                                    .addComponent(jLabel2))
                                .addGroup(panelAutorLayout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(txtCodAut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAgregarAuto))
                                .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelAutorLayout.createSequentialGroup()
                                        .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(panelAutorLayout.createSequentialGroup()
                                                .addComponent(txtNomAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(21, 21, 21))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAutorLayout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addComponent(btnModifAutor))
                                    .addComponent(txtNaciAutor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelAutorLayout.createSequentialGroup()
                                .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelAutorLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(96, 96, 96))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAutorLayout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel5)
                                        .addGap(61, 61, 61))
                                    .addGroup(panelAutorLayout.createSequentialGroup()
                                        .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtSeudonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelAutorLayout.createSequentialGroup()
                                                .addComponent(rbtnMasculino)
                                                .addGap(37, 37, 37)
                                                .addComponent(rbtnFemenino)))
                                        .addGap(27, 27, 27)))
                                .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelAutorLayout.createSequentialGroup()
                                        .addComponent(btnSalirAutor)
                                        .addGap(16, 16, 16))
                                    .addComponent(btnElimAutor, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(panelAutorLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panelAutorLayout.setVerticalGroup(
            panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutorLayout.createSequentialGroup()
                .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAutorLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(panelAutorLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCodAut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAgregarAuto)
                                .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAutorLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnModifAutor))
                    .addGroup(panelAutorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(txtNaciAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(btnElimAutor))
                .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAutorLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnSalirAutor)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelAutorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSeudonimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnFemenino)
                            .addComponent(rbtnMasculino))
                        .addGap(29, 29, 29))))
        );

        TableAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableAutorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableAutor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAutorActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirAutorActionPerformed

    private void TableAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableAutorMouseClicked
        int f=TableAutor.getSelectedRow();
       txtCodAut.setText(TableAutor.getValueAt(f, 0).toString());
       txtNomAuto.setText(TableAutor.getValueAt(f, 1).toString());
       txtSeudonimo.setText(TableAutor.getValueAt(f, 2).toString()); 
       txtNaciAutor.setText(TableAutor.getValueAt(f, 3).toString());
       
    }//GEN-LAST:event_TableAutorMouseClicked

    private void btnAgregarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAutoActionPerformed
         ob.agregar(txtNomAuto.getText(),txtSeudonimo.getText(),rbtnMasculino.getText(),txtNaciAutor.getText(),Integer.parseInt(txtestado.getText()));
          llenar();
          limpiar();
    }//GEN-LAST:event_btnAgregarAutoActionPerformed

    private void btnModifAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifAutorActionPerformed
      ob.modificar( txtCodAut.getText(),txtNomAuto.getText(),txtSeudonimo.getText(),rbtnMasculino.getText(),txtNaciAutor.getText());
          limpiar();
          llenar();
    }//GEN-LAST:event_btnModifAutorActionPerformed

    private void btnElimAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimAutorActionPerformed
        ob.eliminar( txtCodAut.getText());
          llenar();
          limpiar();
    }//GEN-LAST:event_btnElimAutorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableAutor;
    private javax.swing.JButton btnAgregarAuto;
    private javax.swing.JButton btnElimAutor;
    private javax.swing.JButton btnModifAutor;
    private javax.swing.JButton btnSalirAutor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelAutor;
    private javax.swing.JRadioButton rbtnFemenino;
    private javax.swing.JRadioButton rbtnMasculino;
    private javax.swing.JTextField txtCodAut;
    private javax.swing.JTextField txtNaciAutor;
    private javax.swing.JTextField txtNomAuto;
    private javax.swing.JTextField txtSeudonimo;
    private javax.swing.JTextField txtestado;
    // End of variables declaration//GEN-END:variables
}
