/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem.Presentacion;

/**
 *
 * @author Brenda Ramos
 */
public class Frm_Libro extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_Libro
     */
    public Frm_Libro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLibro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodLib = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTituloLib = new javax.swing.JTextField();
        txtPrecioLib = new javax.swing.JTextField();
        txtTomoLib = new javax.swing.JTextField();
        txtPublicacionLib = new javax.swing.JTextField();
        cmbAutorLib = new javax.swing.JComboBox<>();
        cmbEditorialLib = new javax.swing.JComboBox<>();
        cmbCategoriaLib = new javax.swing.JComboBox<>();
        btnAgregarLib = new javax.swing.JButton();
        btnMOdifLib = new javax.swing.JButton();
        btnELiminLib = new javax.swing.JButton();
        btnComprarLib = new javax.swing.JButton();
        txtExistenciasLib = new javax.swing.JTextField();
        btnPrestarLib = new javax.swing.JButton();
        btnSalirLib = new javax.swing.JButton();
        txtIdUsuarioFK = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableLibro = new javax.swing.JTable();

        setTitle("Libro");

        jLabel1.setText("Código");

        jLabel2.setText("Titulo");

        jLabel3.setText("Año de Publicación");

        jLabel4.setText("Categoria");

        jLabel5.setText("Existencias");

        txtCodLib.setEditable(false);

        jLabel6.setText("Tomo");

        jLabel7.setText("Autor");

        jLabel8.setText("Editorial");

        jLabel9.setText("Precio");

        txtTomoLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTomoLibActionPerformed(evt);
            }
        });

        btnAgregarLib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/agregar-boton-dentro-del-circulo-negro.png"))); // NOI18N
        btnAgregarLib.setText("Agregar");

        btnMOdifLib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/lapiz-escribiendo-en-un-papel.png"))); // NOI18N
        btnMOdifLib.setText("Modificar");

        btnELiminLib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/cesto-de-basura.png"))); // NOI18N
        btnELiminLib.setText("Eliminar");

        btnComprarLib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/carro-de-la-compra.png"))); // NOI18N
        btnComprarLib.setText("Comprar");

        btnPrestarLib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/pagar.png"))); // NOI18N
        btnPrestarLib.setText("Prestar");

        btnSalirLib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/logout.png"))); // NOI18N
        btnSalirLib.setText("Salir");
        btnSalirLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirLibActionPerformed(evt);
            }
        });

        txtIdUsuarioFK.setEditable(false);
        txtIdUsuarioFK.setBorder(null);
        txtIdUsuarioFK.setEnabled(false);

        javax.swing.GroupLayout PanelLibroLayout = new javax.swing.GroupLayout(PanelLibro);
        PanelLibro.setLayout(PanelLibroLayout);
        PanelLibroLayout.setHorizontalGroup(
            PanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLibroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelLibroLayout.createSequentialGroup()
                        .addGroup(PanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelLibroLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtTituloLib))
                            .addGroup(PanelLibroLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPublicacionLib, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                            .addGroup(PanelLibroLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbCategoriaLib, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PanelLibroLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtExistenciasLib)))
                        .addGap(47, 47, 47)
                        .addGroup(PanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrecioLib)
                            .addComponent(txtTomoLib)
                            .addComponent(cmbAutorLib, 0, 190, Short.MAX_VALUE)
                            .addComponent(cmbEditorialLib, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelLibroLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodLib, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                        .addComponent(txtIdUsuarioFK, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLibroLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(PanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarLib, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnELiminLib, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSalirLib)
                                .addComponent(btnPrestarLib))))
                    .addGroup(PanelLibroLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnMOdifLib))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLibroLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnComprarLib, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        PanelLibroLayout.setVerticalGroup(
            PanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLibroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdUsuarioFK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(txtTituloLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTomoLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(PanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(txtPublicacionLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAutorLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(PanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(cmbEditorialLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCategoriaLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(txtPrecioLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExistenciasLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(PanelLibroLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnAgregarLib)
                .addGap(18, 18, 18)
                .addComponent(btnMOdifLib)
                .addGap(18, 18, 18)
                .addComponent(btnELiminLib)
                .addGap(18, 18, 18)
                .addComponent(btnComprarLib)
                .addGap(18, 18, 18)
                .addComponent(btnPrestarLib)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalirLib)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TableLibro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                    .addComponent(PanelLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTomoLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTomoLibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTomoLibActionPerformed

    private void btnSalirLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirLibActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirLibActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLibro;
    private javax.swing.JTable TableLibro;
    private javax.swing.JButton btnAgregarLib;
    private javax.swing.JButton btnComprarLib;
    private javax.swing.JButton btnELiminLib;
    private javax.swing.JButton btnMOdifLib;
    private javax.swing.JButton btnPrestarLib;
    private javax.swing.JButton btnSalirLib;
    private javax.swing.JComboBox<String> cmbAutorLib;
    private javax.swing.JComboBox<String> cmbCategoriaLib;
    private javax.swing.JComboBox<String> cmbEditorialLib;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodLib;
    private javax.swing.JTextField txtExistenciasLib;
    private javax.swing.JTextField txtIdUsuarioFK;
    private javax.swing.JTextField txtPrecioLib;
    private javax.swing.JTextField txtPublicacionLib;
    private javax.swing.JTextField txtTituloLib;
    private javax.swing.JTextField txtTomoLib;
    // End of variables declaration//GEN-END:variables
}
