package sistem.Presentacion;

import java.awt.Dimension;
//import sistem.Presentacion.Frm_Usuario;

/**
 * nombre de la clase: Frm_MDI
 * version:1.0
 * fecha: 23/08/19
 * copyright:ITCA-FEPADE
 * @author Brenda Ramos
 */
public class Frm_MDIl extends javax.swing.JFrame {

    /**
     * Creates new form Frm_MDIl
     */
    public Frm_MDIl() {
        initComponents();
        this.setExtendedState(Frm_MDIl.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        MenuBar = new javax.swing.JMenuBar();
        UserMenu = new javax.swing.JMenu();
        MenuItemUser = new javax.swing.JMenuItem();
        MenuItemEmpl = new javax.swing.JMenuItem();
        EditorialMenu = new javax.swing.JMenu();
        MenuItemEditorial = new javax.swing.JMenuItem();
        LibroMenu = new javax.swing.JMenu();
        MenuItemLibro = new javax.swing.JMenuItem();
        CategMenu = new javax.swing.JMenu();
        MenuItemCateg = new javax.swing.JMenuItem();
        AutoresMenu = new javax.swing.JMenu();
        MenuItemAutor = new javax.swing.JMenuItem();
        PrestamoMenu = new javax.swing.JMenu();
        MenuItemPrestamo = new javax.swing.JMenuItem();
        CompraMenu = new javax.swing.JMenu();
        MenuItemCompra = new javax.swing.JMenuItem();
        VentaMenu = new javax.swing.JMenu();
        MenuItemVenta = new javax.swing.JMenuItem();
        ReporteMenu = new javax.swing.JMenu();
        SalirMenu = new javax.swing.JMenu();
        SalirMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        UserMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/empleado.png"))); // NOI18N
        UserMenu.setText("Usuario");

        MenuItemUser.setText("Agregar Usuario");
        MenuItemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemUserActionPerformed(evt);
            }
        });
        UserMenu.add(MenuItemUser);

        MenuItemEmpl.setText("Agregar Empleado");
        UserMenu.add(MenuItemEmpl);

        MenuBar.add(UserMenu);

        EditorialMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/colegio.png"))); // NOI18N
        EditorialMenu.setText("Editorial");

        MenuItemEditorial.setText("Agregar Editorial");
        MenuItemEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEditorialActionPerformed(evt);
            }
        });
        EditorialMenu.add(MenuItemEditorial);

        MenuBar.add(EditorialMenu);

        LibroMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/libro.png"))); // NOI18N
        LibroMenu.setText("Libro");

        MenuItemLibro.setText("Agregar Libro");
        MenuItemLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLibroActionPerformed(evt);
            }
        });
        LibroMenu.add(MenuItemLibro);

        MenuBar.add(LibroMenu);

        CategMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/categoria.png"))); // NOI18N
        CategMenu.setText("Categoria");

        MenuItemCateg.setText("Agregar Categoria");
        MenuItemCateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCategActionPerformed(evt);
            }
        });
        CategMenu.add(MenuItemCateg);

        MenuBar.add(CategMenu);

        AutoresMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/escritor.png"))); // NOI18N
        AutoresMenu.setText("Autores");

        MenuItemAutor.setText("Agregar Autores");
        MenuItemAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAutorActionPerformed(evt);
            }
        });
        AutoresMenu.add(MenuItemAutor);

        MenuBar.add(AutoresMenu);

        PrestamoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/venta.png"))); // NOI18N
        PrestamoMenu.setText("Prestamo");

        MenuItemPrestamo.setText("Agregar Prestamo");
        PrestamoMenu.add(MenuItemPrestamo);

        MenuBar.add(PrestamoMenu);

        CompraMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/bienes.png"))); // NOI18N
        CompraMenu.setText("Compra");

        MenuItemCompra.setText("Agregar Compra");
        CompraMenu.add(MenuItemCompra);

        MenuBar.add(CompraMenu);

        VentaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/venta (1).png"))); // NOI18N
        VentaMenu.setText("Venta");

        MenuItemVenta.setText("agregar Venta");
        VentaMenu.add(MenuItemVenta);

        MenuBar.add(VentaMenu);

        ReporteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/crecimiento.png"))); // NOI18N
        ReporteMenu.setText("Reportes");
        MenuBar.add(ReporteMenu);

        SalirMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/Presentacion/img/borrar (1).png"))); // NOI18N
        SalirMenu.setText("Salir");

        SalirMenuItem.setText("Salir");
        SalirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirMenuItemActionPerformed(evt);
            }
        });
        SalirMenu.add(SalirMenuItem);

        MenuBar.add(SalirMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//usuario formulario
    private void MenuItemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemUserActionPerformed
        Frm_Usuario user= new Frm_Usuario();
        jDesktopPanePrincipal.add(user);
        //codigo para centrar el internalframe
        Dimension desktopSize = jDesktopPanePrincipal.getSize();
        Dimension FrameSize = user.getSize();
        user.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        user.show();
    }//GEN-LAST:event_MenuItemUserActionPerformed
//Salir
    private void SalirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirMenuItemActionPerformed
//formulario editorial
    private void MenuItemEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEditorialActionPerformed
        Frm_Editorial editorial = new Frm_Editorial();
        jDesktopPanePrincipal.add(editorial);
        Dimension desktopSize = jDesktopPanePrincipal.getSize();
        Dimension FrameSize = editorial.getSize();
        editorial.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        editorial.show();
    }//GEN-LAST:event_MenuItemEditorialActionPerformed
//formulario libro
    private void MenuItemLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLibroActionPerformed
        Frm_Libro libro = new Frm_Libro();
        jDesktopPanePrincipal.add(libro);
        Dimension desktopSize = jDesktopPanePrincipal.getSize();
        Dimension FrameSize = libro.getSize();
        libro.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        libro.show();
    }//GEN-LAST:event_MenuItemLibroActionPerformed
///formulario Autor
    private void MenuItemAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAutorActionPerformed
        Frm_Autor autor = new Frm_Autor();
        jDesktopPanePrincipal.add(autor);
        Dimension desktopSize = jDesktopPanePrincipal.getSize();
        Dimension FrameSize = autor.getSize();
        autor.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        autor.show();
    }//GEN-LAST:event_MenuItemAutorActionPerformed
//formulario categoria
    private void MenuItemCategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCategActionPerformed
        Frm_Categoria categ = new Frm_Categoria();
        jDesktopPanePrincipal.add(categ);
        Dimension desktopSize = jDesktopPanePrincipal.getSize();
        Dimension FrameSize = categ.getSize();
        categ.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        categ.show();
    }//GEN-LAST:event_MenuItemCategActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_MDIl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_MDIl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_MDIl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_MDIl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_MDIl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AutoresMenu;
    private javax.swing.JMenu CategMenu;
    private javax.swing.JMenu CompraMenu;
    private javax.swing.JMenu EditorialMenu;
    private javax.swing.JMenu LibroMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem MenuItemAutor;
    private javax.swing.JMenuItem MenuItemCateg;
    private javax.swing.JMenuItem MenuItemCompra;
    private javax.swing.JMenuItem MenuItemEditorial;
    private javax.swing.JMenuItem MenuItemEmpl;
    private javax.swing.JMenuItem MenuItemLibro;
    private javax.swing.JMenuItem MenuItemPrestamo;
    private javax.swing.JMenuItem MenuItemUser;
    private javax.swing.JMenuItem MenuItemVenta;
    private javax.swing.JMenu PrestamoMenu;
    private javax.swing.JMenu ReporteMenu;
    private javax.swing.JMenu SalirMenu;
    private javax.swing.JMenuItem SalirMenuItem;
    private javax.swing.JMenu UserMenu;
    private javax.swing.JMenu VentaMenu;
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    // End of variables declaration//GEN-END:variables
}
