-- MySQL Script generated by MySQL Workbench
-- Sat Aug 24 10:32:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema libreria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema libreria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `libreria` DEFAULT CHARACTER SET latin1 ;
USE `libreria` ;

-- -----------------------------------------------------
-- Table `libreria`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`autor` (
  `id_autor` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `genero` VARCHAR(20) NOT NULL,
  `nacionalidad` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `libreria`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`categoria` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_cat` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `libreria`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`compra` (
  `id_compra` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `total` DOUBLE NOT NULL,
  `iva` DOUBLE NOT NULL,
  PRIMARY KEY (`id_compra`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `libreria`.`editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`editorial` (
  `id_edit` INT(11) NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(12) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `pais` VARCHAR(30) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_edit`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `libreria`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`rol` (
  `id_rol` INT(11) NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `libreria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(30) NOT NULL,
  `pass` VARCHAR(30) NOT NULL,
  `edad` INT(11) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `id_rol` INT(11) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_id_rol` (`id_rol` ASC),
  CONSTRAINT `fk_id_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `libreria`.`rol` (`id_rol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `libreria`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`libro` (
  `id_libro` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NOT NULL,
  `Existencias` INT(11) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `anio_public` DATE NOT NULL,
  `tomo` DOUBLE NOT NULL,
  `id_categoria` INT(11) NOT NULL,
  `id_autor` INT(11) NOT NULL,
  `id_edit` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_libro`),
  INDEX `fk_id_categoria` (`id_categoria` ASC),
  INDEX `fk_id_autor` (`id_autor` ASC),
  INDEX `fk_id_edit` (`id_edit` ASC),
  INDEX `fk_id_usuario` (`id_usuario` ASC),
  CONSTRAINT `fk_id_autor`
    FOREIGN KEY (`id_autor`)
    REFERENCES `libreria`.`autor` (`id_autor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `libreria`.`categoria` (`id_categoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_edit`
    FOREIGN KEY (`id_edit`)
    REFERENCES `libreria`.`editorial` (`id_edit`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `libreria`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `libreria`.`detalle_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`detalle_compra` (
  `id_libro` INT(11) NOT NULL,
  `id_compra` INT(11) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `subtotal` DOUBLE NOT NULL,
  `id_detalle_compra` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_detalle_compra`),
  INDEX `fk_id_libro` (`id_libro` ASC),
  INDEX `fk_id_compra` (`id_compra` ASC),
  CONSTRAINT `fk_id_compra`
    FOREIGN KEY (`id_compra`)
    REFERENCES `libreria`.`compra` (`id_compra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_libro`
    FOREIGN KEY (`id_libro`)
    REFERENCES `libreria`.`libro` (`id_libro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `libreria`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`prestamo` (
  `id_prestamo` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATE NOT NULL,
  `fecha_final` DATE NOT NULL,
  `cargos` DOUBLE NOT NULL,
  `total` DOUBLE NOT NULL,
  PRIMARY KEY (`id_prestamo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `libreria`.`detalle_prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`detalle_prestamo` (
  `id_libro` INT(11) NOT NULL,
  `id_prestamo` INT(11) NOT NULL,
  `subtotal` DOUBLE NOT NULL,
  `id_detalle_prestamo` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_detalle_prestamo`),
  INDEX `fk_id_libros` (`id_libro` ASC),
  INDEX `fk_id_prestamos` (`id_prestamo` ASC),
  CONSTRAINT `fk_id_libros`
    FOREIGN KEY (`id_libro`)
    REFERENCES `libreria`.`libro` (`id_libro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_prestamos`
    FOREIGN KEY (`id_prestamo`)
    REFERENCES `libreria`.`prestamo` (`id_prestamo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
